# Configuration for dotupdate.py
# Files and directories to ignore when discovering dotfiles in the repository

ignore_items:
  - old
  - .git
  - .gitignore
  - .gitconfig

  - dotupdate.py
  - dotupdate.config.yaml
  - Makefile

# custom configs to ignore
  - .config/github-copilot
  - .config/gcloud
  - .config/mps-youtube
  - .config/configstore
  - .config/iterm2/AppSupport
  - .config/iterm2/sockets
  - .config/Battle.net/
  - .config/filezilla/
  - .config/menus/
  - .config/pudb/
  - .config/mgba/
