# Configuration for dotupdate.py
# Files and directories to ignore when discovering dotfiles in the repository

ignore_items:
  # Git files
  - .git
  - .gitignore
  - .gitconfig

  # Documentation
  - MAC_GET_STARTED.md
  - SETUP.md
  - README.md

  # Scripts and programs
  - update.sh
  - updatefiles.py
  - updatefiles_v2.py
  - dotupdate.py
  - dotupdate.config.yaml

  # Platform-specific
  - windows-terminal
  - com.googlecode.iterm2.plist

  # IDE/Editor configurations
  - .config/github-copilot
